version: '3.8'

services:
  dynamodb-local:
    image: amazon/dynamodb-local
    container_name: dynamodb-local
    command: '-jar DynamoDBLocal.jar -inMemory -sharedDb'
    ports:
      - '8000:8000'
    # If you want data persisted between restarts, uncomment:
    # volumes:
    #   - ./dynamodb_data:/home/dynamodblocal/data

  # Optional: LocalStack for other AWS services
  # localstack:
  #   image: localstack/localstack:latest
  #   container_name: localstack
  #   environment:
  #     SERVICES: dynamodb,s3,sqs,sns,cognito
  #     DEBUG: "1"
  #   ports:
  #     - "4566:4566"
  #     - "4571:4571"
